# fly.toml app configuration file generated for grocery-admin-wispy-sun-6673 on 2025-03-28T10:11:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grocery-admin-wispy-sun-6673'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
